config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :medications, shallow: true do
    resources :medication_versions do
      resources :prescriptions, only: %i[ new create ]
    end
  end

  resources :prescriptions, except: %i[ new create ] do
    resources :packs
    resources :doses
  end

  resources :active_ingredients
  resources :labelers
  resource :assistent_talks
  resources :users
  get "profile" => "users#profile"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "site#index"

  get "landing" => "site#landing"
  get "about" => "site#about"

  get "legal/imprint", as: :imprint
  get "legal/terms-of-service", as: :terms_of_service
  get "legal/privacy", as: :privacy

  get "search" => "search#index"

  get "timeline" => "timeline#index"
  get "calendar" => "calendar#index"
end

app/models/assistent_talk.rb
class AssistentTalk < ApplicationRecord
  belongs_to :user

  validates :talk, presence: true

  enum :talk, {
    introduction: 0
  }, validate: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :medications

  validates :name, presence: true, uniqueness: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :prescription

  validates :amount_taken, presence: true, numericality: true, comparison: { greater_than: 0, less_than_or_equal_to: ->(record) { record.prescription&.remaining_units } }
  validates :taken_at, presence: true, comparison: { less_than_or_equal_to: -> { Time.current } }
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :medications

  validates :name, presence: true, uniqueness: true
end

app/models/labeler.rb
class Labeler < ApplicationRecord
  has_many :medications

  validates :name, presence: true, uniqueness: true
end

app/models/medication.rb
class Medication < ApplicationRecord
  has_one_attached :image

  belongs_to :labeler, optional: true
  belongs_to :form
  has_rich_text :notes

  has_many :versions, class_name: "MedicationVersion", foreign_key: "medication_id", dependent: :destroy

  has_and_belongs_to_many :active_ingredients
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :references

  validates :name, presence: true
end

app/models/pack.rb
class Pack < ApplicationRecord
  belongs_to :prescription

  validates :amount, presence: true, numericality: { only_integer: true }, comparison: { greater_than: 0 }
  validates :aquired_at, presence: true, comparison: { less_than_or_equal_to: -> { Time.current } }
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  belongs_to :medication_version

  has_many :packs, dependent: :destroy
  has_many :doses, dependent: :destroy


  delegate :strength_per_dose, to: :medication_version, allow_nil: true
  delegate :form, to: :medication_version, allow_nil: true
  delegate :unit, to: :medication_version, allow_nil: true
  delegate :full_name, to: :medication_version, allow_nil: true

  validates :dosage, presence: true, numericality: { only_integer: true }

  def remaining_units
    total_units = packs.sum(:amount)
    used_units = doses.sum(:amount_taken)
    total_units - used_units
  end

  def remaining_doses
    ((remaining_units() * medication_version.strength_per_dose) / dosage).round(2)
  end
end

app/models/reference.rb
class Reference < ApplicationRecord
  has_and_belongs_to_many :medications

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :terms_of_service

  has_secure_password

  scope :admins, -> { where(role: "admin") }
  scope :users, -> { where(role: "user") }

  has_many :sessions, dependent: :destroy
  has_many :assistent_talks, dependent: :destroy
  has_many :prescriptions, dependent: :destroy
  has_many :medication_versions, through: :prescriptions
  has_many :doses, through: :prescriptions

  encrypts :email_address, deterministic: true
  encrypts :username

  validates :email_address, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, presence: true
  validates :terms_of_service, acceptance: true, on: :create

  enum :role, { user: 0, admin: 1 }, validate: true
  enum :pfp, {
    "medicine_kisser": 0,
    "ritalin_kisser": 1,
    "modafinil_kisser": 2,
    "kisser_kisser": 3,
    "home_kisser": 4
  }, validate: true

  def profile_picture
    "pfps/#{pfp}.png"
  end

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/user_medication.rb
class UserMedication < ApplicationRecord
  belongs_to :user
  belongs_to :medication_version

  has_many :packs, dependent: :destroy
  has_many :doses, through: :packs

  delegate :form, to: :medication_version, allow_nil: true

  validates :dosage, presence: true, numericality: { only_integer: true }

  def remaining_units
    total_units = packs.sum(:amount)
    used_units = doses.sum(:amount_taken)
    total_units - used_units
  end

  def remaining_doses
    ((remaining_units() * medication_version.strength_per_dose) / dosage).round(2)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:query]

    @active_ingredients = ActiveIngredient.where("LOWER(name) LIKE LOWER(?)", "%#{@query}%")
    @categories = Category.where("LOWER(name) LIKE LOWER(?)", "%#{@query}%")
    @labelers = Labeler.where("LOWER(name) LIKE LOWER(?)", "%#{@query}%")
    @medications = Medication.where("LOWER(name) LIKE LOWER(?)", "%#{@query}%")
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/search/index.html.erb
<div class="w-full">
  <section>
    <h3 class="text-3xl">Search</h3>

    <%= form_with url: search_path, class: "mt-4", method: :get, data: { controller: "search" } do |form| %>
      <div class="flex">
        <%= form.text_field :query, value: @query, placeholder: "Search for anything your heart desires ^w^", class: "shadow-sm rounded-md border bg-rose-50 border-rose-300 px-3 py-2 w-full mr-2" %>
        <%= form.submit "Yippie", class: "rounded-md px-6 py-3 bg-rose-400 hover:bg-rose-300 cursor-pointer font-medium" %>
      </div>
      <div class="mt-1 flex items-center justify-end">
        <button data-action="search#toggleHiddenOptions" type="button" class="no-js:hidden hover:cursor-pointer">Advanced search</button>
      </div>
      <div data-search-target="hiddenOptions" class="js:hidden">
        Hidden options
      </div>
    <% end %>
  </section>

  <section class="mt-12">
    <h3 class="text-3xl border-b">Results</h3>
    <% if @categories.any? %>
      <div class="flex flex-wrap justify-baseline">
        <% @categories.each do |category| %>
          <%= link_to category.name, root_path, class: "p-3 m-1 bg-rose-50 border border-rose-300 rounded-full text-nowrap border-r" %>
        <% end %>
      </div>
    <% end %>

    <% if @medications.any? %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">Medications</h4>
        <% if admin? %>
          <%= link_to "Add new", new_medication_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>

      <div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-3">
        <% @medications.each do |medication| %>
          <%= render "medications/card", medication: medication %>
        <% end %>
      </div>
    <% else %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">No medications found</h4>
        <% if admin? %>
          <%= link_to "Add new", new_medication_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>

    <% end %>


    <% if @active_ingredients.any? %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">Active ingredients</h4>
        <% if admin? %>
          <%= link_to "Add new", new_active_ingredient_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>

      <% @active_ingredients.each do |active_ingredient| %>
        <%= active_ingredient.name %>
      <% end %>
    <% else %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">No active ingredients found</h4>
        <% if admin? %>
          <%= link_to "Add new", new_active_ingredient_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>

    <% end %>


    <% if @labelers.any? %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">Labelers</h4>
        <% if admin? %>
          <%= link_to "Add new", new_labeler_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>

      <div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">
        <%= render @labelers %>
      </div>
    <% else %>
      <div class="mt-6 mb-2 flex items-center justify-between md:justify-start">
        <h4 class="text-2xl">No labelers found</h4>
        <% if admin? %>
          <%= link_to "Add new", new_labeler_path, class: "ml-3 text-zinc-600 italic" %>
        <% end %>
      </div>
    <% end %>
  </section>
</div>